create table Payout_Sheet
(
    `Agent Type` VARCHAR(50),
    `Associate Code` VARCHAR(20),
    `Region` VARCHAR(50),
    `Agent PAN` VARCHAR(10),
    `GST Number` VARCHAR(15),
    `Channel` VARCHAR(50),
    `Channel Code` VARCHAR(20),
    `Cordinator Code` VARCHAR(20),
    `Agent Licence No` VARCHAR(30),
    `Customer First Name` VARCHAR(100),
    `Customer Middle Name` VARCHAR(100),
    `Customer Last Name` VARCHAR(100),
    `Customer Type` VARCHAR(50),
    `Business Type` VARCHAR(100),
    `Product type` VARCHAR(100),
    `Coverage Type` VARCHAR(100),
    `Policy Number` VARCHAR(30) PRIMARY KEY,
    `Policy` VARCHAR(100),
    `Policy Issue Date` DATE,
    `Start Date` DATE,
    `Expiry Date` DATE,
    `Payment Date` DATE,
    `Insurer` VARCHAR(100),
    `Product Name` VARCHAR(100),
    `Previous Insurance Company` VARCHAR(100),
    `Policy Term` INT,
    `Premium Payment Term` INT,
    `Premium Payment Frequency` VARCHAR(30),
    `Sum Insured` DECIMAL(15,2),
    `OD Start Date` DATE,
    `OD End Date` DATE,
    `OD Year` INT,
    `TP Start Date` DATE,
    `TP End Date` DATE,
    `TP Year` INT,
    `RTO State` VARCHAR(50),
    `RTO City` VARCHAR(50),
    `Vehicle Type` VARCHAR(50),
    `Vehicle Registration No` VARCHAR(20),
    `Vehicle Registration Date` DATE,
    `Vehicle Manufacture` VARCHAR(100),
    `Vehicle Make Model` VARCHAR(100),
    `Vehicle Engine No` VARCHAR(50),
    `Vehicle Chassis No` VARCHAR(50),
    `GVW` VARCHAR(20),
    `Vehicle Cubic Capacity` INT,
    `Vehicle Seat Capacity` INT,
    `Fuel` VARCHAR(20),
    `NCB` VARCHAR(20),
    `IDV` DECIMAL(15,2),
    `OD Premium Amount` DECIMAL(15,2),
    `TP Premium Amount` DECIMAL(15,2),
    `CPA` DECIMAL(15,2),
    `Net Premium` DECIMAL(15,2),
    `GST` DECIMAL(15,2),
    `Gross Premium Amount` DECIMAL(15,2),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;